[package]
name = "kurookku/replicaservice"
description = "ReplicaService forked from Madwork but includes Replica:Observe method"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json"]

[dependencies]
